In [1]:
import pandas as pd
import numpy as np

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
df=pd.read_csv('C:/Users/hrush/laptop_price.csv')
df.head()

Brand Processor Operating System RAM Type RAM Size Disc Type Disc Size  \
0  Lenovo     Intel       Windows 11     DDR4      8GB       SSD     256GB   
1  Lenovo     Intel       Windows 11     DDR4      8GB       SSD     512GB   
2    ASUS     Intel       Windows 11     DDR4      8GB       SSD     512GB   
3      HP       AMD       Windows 10     DDR4      8GB       SSD     512GB   
4    ASUS     Intel       Windows 11     DDR4      8GB       SSD     512GB   

     MRP  
0  36990  
1  39990  
2  32990  
3  49990  
4  49990

In [4]:
data=df.copy()

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 720 entries, 0 to 719
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   Brand             720 non-null    object
 1   Processor         720 non-null    object
 2   Operating System  720 non-null    object
 3   RAM Type          720 non-null    object
 4   RAM Size          720 non-null    object
 5   Disc Type         720 non-null    object
 6   Disc Size         720 non-null    object
 7   MRP               720 non-null    int64 
dtypes: int64(1), object(7)
memory usage: 45.1+ KB


In [6]:
data.shape

(720, 8)

## Convert categorical columns to numeric column

### 1.Brand

In [7]:
data['Brand'].unique()

array(['Lenovo', 'ASUS', 'HP', 'DELL', 'RedmiBook', 'realme', 'acer',
       'MSI', 'APPLE', 'Infinix', 'SAMSUNG', 'Ultimus', 'Vaio',
       'GIGABYTE', 'Nokia', 'ALIENWARE'], dtype=object)

In [8]:
def replace_brand(brand):
    if brand=='Lenovo':
        return 1
    elif brand=='ASUS':
        return 2
    elif brand=='HP':
        return 3
    elif brand=='DELL':
        return 4
    elif brand=='RedmiBook':
        return 5
    elif brand=='realme':
        return 6
    elif brand=='acer':
        return 7
    elif brand=='MSI':
        return 8
    elif brand=='APPLE':
        return 9
    elif brand=='Infinix':
        return 10
    elif brand=='SAMSUNG':
        return 11
    elif brand=='Ultimus':
        return 12
    elif brand=='Vaio':
        return 13
    elif brand=='GIGABYTE':
        return 14
    elif brand=='Nokia':
        return 15
    elif brand=='ALIENWARE':
        return 16
    
data['Brand']=data['Brand'].apply(replace_brand)
data['Brand'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
      dtype=int64)

### 2.Processor Type

In [9]:
data['Processor'].unique()

array(['Intel', 'AMD', 'Apple', 'Qualcomm'], dtype=object)

In [10]:
data['Processor'].nunique()

4

In [11]:
def replace_processor(Processor):
    if Processor=='Intel':
        return 1
    elif Processor=='AMD':
        return 2
    elif Processor=='Apple':
        return 3
    elif Processor=='Qualcomm':
        return 4
    
data['Processor']=data['Processor'].apply(replace_processor)
data['Processor'].unique()

array([1, 2, 3, 4], dtype=int64)

### 3.Ram Type

In [12]:
data['RAM Type'].unique()

array(['DDR4', 'DDR5', 'LPDDR4', 'Unified', 'LPDDR4X', 'LPDDR5', 'LPDDR3'],
      dtype=object)

In [13]:
def replace_ram_type(ram_type):
    if ram_type=='DDR4':
        return 1
    elif ram_type=='DDR5':
        return 2
    elif ram_type=='LPDDR4':
        return 3
    elif ram_type=='Unified':
        return 4
    elif ram_type=='LPDDR4X':
        return 5
    elif ram_type=='LPDDR5':
        return 6
    elif ram_type=='LPDDR3':
        return 7
    
data['RAM Type']=data['RAM Type'].apply(replace_ram_type)
data['RAM Type'].unique()

array([1, 2, 3, 4, 5, 6, 7], dtype=int64)

### 4.Ram Size

In [14]:
data['RAM Size'].unique()

array(['8GB', '16GB', '4GB', '32GB'], dtype=object)

In [15]:
def replace_ram_size(ram_size):
    if ram_size=='8GB':
        return 1
    elif ram_size=='16GB':
        return 2
    elif ram_size=='4GB':
        return 3
    elif ram_size=='32GB':
        return 4

    
data['RAM Size']=data['RAM Size'].apply(replace_ram_size)
data['RAM Size'].unique()

array([1, 2, 3, 4], dtype=int64)

### 5.Disc Type

In [16]:
data['Disc Type'].unique()

array(['SSD', 'HDD', 'EMMC'], dtype=object)

In [17]:
def replace_disc_type(disc_type):
    if disc_type=='SSD':
        return 1
    elif disc_type=='HDD':
        return 2
    elif disc_type=='EMMC':
        return 3

    
data['Disc Type']=data['Disc Type'].apply(replace_disc_type)
data['Disc Type'].unique()

array([1, 2, 3], dtype=int64)

### 6.Disc Size

In [18]:
data['Disc Size'].unique()

array(['256GB', '512GB', '1TB', '128GB', '64GB', '32GB', '2TB'],
      dtype=object)

In [19]:
def replace_disc_size(disc_size):
    if disc_size=='256GB':
        return 1
    elif disc_size=='512GB':
        return 2
    elif disc_size=='1TB':
        return 3
    elif disc_size=='128GB':
        return 4
    elif disc_size=='64GB':
        return 5
    elif disc_size=='32GB':
        return 6
    elif disc_size=='2TB':
        return 7
    
data['Disc Size']=data['Disc Size'].apply(replace_disc_size)
data['Disc Size'].unique()

array([1, 2, 3, 4, 5, 6, 7], dtype=int64)

### 7.Operating System

In [20]:
data['Operating System'].unique()

array(['Windows 11', 'Windows 10', 'Mac', 'Chrome', 'DOS'], dtype=object)

In [21]:
def replace_os(os):
    if os=='Windows 11':
        return 1
    elif os=='Windows 10':
        return 2
    elif os=='Mac':
        return 3
    elif os=='Chrome':
        return 4
    elif os=='DOS':
        return 5
    
data['Operating System']=data['Operating System'].apply(replace_os)
data['Operating System'].unique()

array([1, 2, 3, 4, 5], dtype=int64)

In [22]:
data.head()

Brand  Processor  Operating System  RAM Type  RAM Size  Disc Type  \
0      1          1                 1         1         1          1   
1      1          1                 1         1         1          1   
2      2          1                 1         1         1          1   
3      3          2                 2         1         1          1   
4      2          1                 1         1         1          1   

   Disc Size    MRP  
0          1  36990  
1          2  39990  
2          2  32990  
3          2  49990  
4          2  49990

In [23]:
data.isna().sum()

Brand               0
Processor           0
Operating System    0
RAM Type            0
RAM Size            0
Disc Type           0
Disc Size           0
MRP                 0
dtype: int64

### Split the data into dependent and independent

In [24]:
X=data.drop('MRP', axis=1).values

In [25]:
X

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 2],
       [2, 1, 1, ..., 1, 1, 2],
       ...,
       [2, 2, 1, ..., 2, 1, 3],
       [2, 1, 1, ..., 2, 1, 2],
       [1, 1, 2, ..., 1, 2, 3]], dtype=int64)

In [26]:
y=data['MRP'].values

# Feature Scailing

In [27]:
from sklearn.preprocessing import StandardScaler

In [28]:
std=StandardScaler()
X=std.fit_transform(X)
print(X)

[[-0.80688224 -0.87423048 -0.46911664 ... -0.76754824 -0.28058001
  -1.45873792]
 [-0.80688224 -0.87423048 -0.46911664 ... -0.76754824 -0.28058001
  -0.31711694]
 [-0.44104142 -0.87423048 -0.46911664 ... -0.76754824 -0.28058001
  -0.31711694]
 ...
 [-0.44104142  0.91906281 -0.46911664 ...  0.65676808 -0.28058001
   0.82450404]
 [-0.44104142 -0.87423048 -0.46911664 ...  0.65676808 -0.28058001
  -0.31711694]
 [-0.80688224 -0.87423048  1.21970327 ... -0.76754824  2.69026717
   0.82450404]]


## Splitting into Train and Test set

In [29]:
from sklearn.model_selection import train_test_split

In [30]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

## Implimenting ML Models

#### 1.linear Regression 

In [31]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr=lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)

In [32]:
from sklearn.metrics import mean_squared_error as mse, r2_score

In [33]:
MSE=mse(y_pred,y_test).round(2)
RMSE=np.sqrt(MSE).round(2)
R2=r2_score(y_pred, y_test).round(2)

In [34]:
accuracy_results=pd.DataFrame({"Model":["Linear Regression"], "MSE":[MSE], "RMSE":[RMSE], "R2 Score":[R2]})
accuracy_results

Model           MSE      RMSE  R2 Score
0  Linear Regression  1.165097e+09  34133.52      0.52

#### 2.KNN Regression

In [35]:
from sklearn.neighbors import KNeighborsRegressor

In [36]:
knn=KNeighborsRegressor(n_neighbors=3)
knn=knn.fit(x_train,y_train)
y_pred=knn.predict(x_test)

In [37]:
MSE=mse(y_pred,y_test).round(2)
RMSE=np.sqrt(MSE).round(2)
R2=r2_score(y_pred, y_test).round(2)

In [38]:
result=pd.DataFrame({"Model":["KNN Regression"], "MSE":[MSE], "RMSE":[RMSE], "R2 Score":[R2]})
results=pd.concat([accuracy_results,result])
results

Model           MSE      RMSE  R2 Score
0  Linear Regression  1.165097e+09  34133.52      0.52
0     KNN Regression  8.127858e+08  28509.40      0.81

#### 3.Decision Tree

In [39]:
from sklearn.tree import DecisionTreeRegressor

In [40]:
dt=DecisionTreeRegressor(random_state=0)
dt.fit(x_train,y_train)
y_pred=dt.predict(x_test)

In [41]:
MSE=mse(y_pred,y_test).round(2)
RMSE=np.sqrt(MSE).round(2)
R2=r2_score(y_pred, y_test).round(2)

result=pd.DataFrame({"Model":["Decision Tree Regression"], "MSE":[MSE], "RMSE":[RMSE], "R2 Score":[R2]})

results=pd.concat([results,result])
results

Model           MSE      RMSE  R2 Score
0         Linear Regression  1.165097e+09  34133.52      0.52
0            KNN Regression  8.127858e+08  28509.40      0.81
0  Decision Tree Regression  5.533518e+08  23523.43      0.85

#### 4.Random Forest

In [42]:
from sklearn.ensemble import RandomForestRegressor

In [43]:
rf=RandomForestRegressor()
rf.fit(x_train,y_train)
y_pred=rf.predict(x_test)

In [44]:
result=pd.DataFrame({"Model":["Random Forest Regression"], "MSE":[MSE], "RMSE":[RMSE], "R2 Score":[R2]})
results=pd.concat([results,result])
results


Model           MSE      RMSE  R2 Score
0         Linear Regression  1.165097e+09  34133.52      0.52
0            KNN Regression  8.127858e+08  28509.40      0.81
0  Decision Tree Regression  5.533518e+08  23523.43      0.85
0  Random Forest Regression  5.533518e+08  23523.43      0.85

#### 5.Gradient boosting

In [45]:
from sklearn.ensemble import GradientBoostingRegressor

In [46]:
grb= GradientBoostingRegressor(n_estimators =100,random_state =0) 
grb.fit(x_train, y_train) 
y_pred = grb.predict(x_test)

In [47]:
MSE=mse(y_pred,y_test).round(2)
RMSE=np.sqrt(MSE).round(2)
R2=r2_score(y_pred, y_test)

In [48]:
result=pd.DataFrame({"Model":["Gradient Boosting Regression"], "MSE":[MSE], "RMSE":[RMSE], "R2 Score":[R2]})
results=pd.concat([results,result])
results

Model           MSE      RMSE  R2 Score
0             Linear Regression  1.165097e+09  34133.52  0.520000
0                KNN Regression  8.127858e+08  28509.40  0.810000
0      Decision Tree Regression  5.533518e+08  23523.43  0.850000
0      Random Forest Regression  5.533518e+08  23523.43  0.850000
0  Gradient Boosting Regression  5.494580e+08  23440.52  0.862283

#### 6. ADA Boost

In [49]:
from sklearn.ensemble import AdaBoostRegressor

In [50]:
ada=AdaBoostRegressor(n_estimators=100,learning_rate=0.001,random_state=0)
ada.fit(x_train,y_train)
y_pred=ada.predict(x_test)

In [51]:
MSE=mse(y_pred,y_test).round(2)
RMSE=np.sqrt(MSE).round(2)
R2=r2_score(y_pred, y_test)

result=pd.DataFrame({"Model":["ADA Boost Regression"], "MSE":[MSE], "RMSE":[RMSE], "R2 Score":[R2]})

results=pd.concat([results,result])
results

Model           MSE      RMSE  R2 Score
0             Linear Regression  1.165097e+09  34133.52  0.520000
0                KNN Regression  8.127858e+08  28509.40  0.810000
0      Decision Tree Regression  5.533518e+08  23523.43  0.850000
0      Random Forest Regression  5.533518e+08  23523.43  0.850000
0  Gradient Boosting Regression  5.494580e+08  23440.52  0.862283
0          ADA Boost Regression  7.588018e+08  27546.36  0.744745

#### 7.XG boost

In [52]:
pip install --user xgboost

Note: you may need to restart the kernel to use updated packages.


In [53]:
from xgboost import XGBRegressor

In [54]:
xgb=XGBRegressor(verbosity=0) 
xgb.fit(x_train,y_train)
y_pred=xgb.predict(x_test)

In [55]:
MSE=mse(y_pred,y_test).round(2)
RMSE=np.sqrt(MSE).round(2)
R2=r2_score(y_pred, y_test)

result=pd.DataFrame({"Model":["XG Boost Regression"], "MSE":[MSE], "RMSE":[RMSE], "R2 Score":[R2]})

results=pd.concat([results,result])
results

Model           MSE      RMSE  R2 Score
0             Linear Regression  1.165097e+09  34133.52  0.520000
0                KNN Regression  8.127858e+08  28509.40  0.810000
0      Decision Tree Regression  5.533518e+08  23523.43  0.850000
0      Random Forest Regression  5.533518e+08  23523.43  0.850000
0  Gradient Boosting Regression  5.494580e+08  23440.52  0.862283
0          ADA Boost Regression  7.588018e+08  27546.36  0.744745
0           XG Boost Regression  5.649938e+08  23769.60  0.845917

### XG boost regressor has high R2 score and low RMSE.SO ,tune this model and select this to predict the price of Laptop.

In [56]:
xgb=XGBRegressor(learning_rate=0.15, n_estimators=50, max_leaves=0, random_state=42)

xgb.fit(x_train,y_train)
y_pred=xgb.predict(x_test)

print(mse(y_pred,y_test).round(2))
print(np.sqrt(mse(y_pred,y_test).round(2)))
print(((r2_score(y_pred, y_test))*100).round(2))

457971928.85
21400.27870963367
86.84


# Using Encoding (OneHotEncoding/Dummies)

In [57]:
data=df.copy()

### Create dummies for all Categorical column

In [58]:
pd.options.display.max_columns=100

In [59]:
data1=pd.get_dummies(data)
data1.head()

MRP  Brand_ALIENWARE  Brand_APPLE  Brand_ASUS  Brand_DELL  \
0  36990                0            0           0           0   
1  39990                0            0           0           0   
2  32990                0            0           1           0   
3  49990                0            0           0           0   
4  49990                0            0           1           0   

   Brand_GIGABYTE  Brand_HP  Brand_Infinix  Brand_Lenovo  Brand_MSI  \
0               0         0              0             1          0   
1               0         0              0             1          0   
2               0         0              0             0          0   
3               0         1              0             0          0   
4               0         0              0             0          0   

   Brand_Nokia  Brand_RedmiBook  Brand_SAMSUNG  Brand_Ultimus  Brand_Vaio  \
0            0                0              0              0           0   
1            0                0              0              0           0   
2            0                0              0              0           0   
3            0                0              0              0           0   
4            0                0              0              0           0   

   Brand_acer  Brand_realme  Processor_AMD  Processor_Apple  Processor_Intel  \
0           0             0              0                0                1   
1           0             0              0                0                1   
2           0             0              0                0                1   
3           0             0              1                0                0   
4           0             0              0                0                1   

   Processor_Qualcomm  Operating System_Chrome  Operating System_DOS  \
0                   0                        0                     0   
1                   0                        0                     0   
2                   0                        0                     0   
3                   0                        0                     0   
4                   0                        0                     0   

   Operating System_Mac  Operating System_Windows 10  \
0                     0                            0   
1                     0                            0   
2                     0                            0   
3                     0                            1   
4                     0                            0   

   Operating System_Windows 11  RAM Type_DDR4  RAM Type_DDR5  RAM Type_LPDDR3  \
0                            1              1              0                0   
1                            1              1              0                0   
2                            1              1              0                0   
3                            0              1              0                0   
4                            1              1              0                0   

   RAM Type_LPDDR4  RAM Type_LPDDR4X  RAM Type_LPDDR5  RAM Type_Unified  \
0                0                 0                0                 0   
1                0                 0                0                 0   
2                0                 0                0                 0   
3                0                 0                0                 0   
4                0                 0                0                 0   

   RAM Size_16GB  RAM Size_32GB  RAM Size_4GB  RAM Size_8GB  Disc Type_EMMC  \
0              0              0             0             1               0   
1              0              0             0             1               0   
2              0              0             0             1               0   
3              0              0             0             1               0   
4              0              0             0             1               0   

   Disc Type_HDD  Disc Type_SSD  Disc Size_128GB  Disc

In [60]:
X=data1.drop("MRP", axis=1).values
y=data1["MRP"].values

In [61]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2, random_state=0)

In [62]:
from sklearn.ensemble import RandomForestRegressor

rf=RandomForestRegressor()
rf=rf.fit(x_train,y_train)
y_pred=rf.predict(x_test)

In [63]:
from sklearn.metrics import r2_score, mean_squared_error

print(r2_score(y_pred,y_test))

0.8822292794900468


In [64]:
from xgboost import XGBRegressor

xgb=XGBRegressor(max_depth=2, max_leaves=2, booster='gbtree', learning_rate=0.19)
xgb=xgb.fit(x_train,y_train)
y_pred=xgb.predict(x_test)

In [65]:
print(r2_score(y_pred,y_test))

0.9194503254451336


In [66]:
from sklearn.model_selection import cross_val_score, KFold, ShuffleSplit

In [67]:
xgb=XGBRegressor(n_estimators=100,max_depth=2, max_leaves=2, booster='gbtree', learning_rate=0.19)

k=ShuffleSplit(n_splits=100, test_size=0.2, random_state=0)
score=cross_val_score(xgb, X,y, cv=k)
print("Cross validations Score:\n", score)
print("Average Cross validations Score:", score.mean())
print("Maximum Cross validations Score:", score.max())
print("Minimum Cross validations Score:", score.min())

Cross validations Score:
 [0.91495966 0.86168018 0.87582945 0.87495164 0.75954796 0.8584843
 0.85802864 0.861162   0.89802215 0.89467985 0.90591489 0.9027385
 0.80068514 0.87119416 0.84570491 0.90027658 0.91734123 0.89167961
 0.8737434  0.86210028 0.81779995 0.77564639 0.87008686 0.85636394
 0.86456345 0.79513169 0.86457515 0.91414549 0.84615609 0.91845645
 0.86076979 0.82577774 0.86356383 0.75768202 0.89336363 0.8824216
 0.77474707 0.86287407 0.74270906 0.821472   0.90838447 0.73386763
 0.88383526 0.86878077 0.84570138 0.90018183 0.83044239 0.75801717
 0.888287   0.74862135 0.78805095 0.90638862 0.83821118 0.88128637
 0.74308117 0.90848259 0.84828986 0.80767976 0.91570959 0.85648085
 0.85429738 0.89273711 0.91752643 0.84750399 0.83238282 0.89484455
 0.75613081 0.92308529 0.88530085 0.80523874 0.89942804 0.8403766
 0.88406558 0.81704577 0.85611929 0.92021717 0.8583537  0.8589777
 0.83303107 0.79486626 0.76482706 0.89590943 0.73198221 0.932207
 0.91704336 0.83780941 0.7816254  0.8729464

# performance of the model is increased

### GridsearchCV

In [70]:
from sklearn.model_selection import GridSearchCV

In [71]:
xgb=XGBRegressor(max_leaves=0)
parameters=dict(n_estimators=[50,60,70,80,90,100], max_depth=[1,2,3,4,5],
                learning_rate=[0.1,0.11,0.12,0.13,0.14,0.15,0.16,0.18,0.19,0.2])
grid_search_cv=GridSearchCV(xgb,param_grid=parameters)
search = grid_search_cv.fit(x_train,y_train)
search.best_params_

{'learning_rate': 0.2, 'max_depth': 1, 'n_estimators': 100}

In [72]:
xgb=XGBRegressor(max_leaves=0, n_estimators=100, max_depth=1, learning_rate=0.2)
xgb=xgb.fit(x_train,y_train)
r2_score(xgb.predict(x_test), y_test)

0.9058283609449451

# Model performance is increased